export const CATEGORY_DIRECTORY = [
  {
    id: 'fragrances',
    slug: 'beauty',
    title: { en: 'Fragrances', ar: 'العطور' },
    subs: [
      { en: "Women's Perfumes", ar: 'عطور نسائية', key: 'women-perfumes' },
      { en: "Men's Perfumes", ar: 'عطور للرجال', key: 'men-perfumes' },
      { en: 'Unisex Perfumes', ar: 'عطور للجنسين', key: 'unisex-perfumes' },
      { en: 'Oriental Perfumes', ar: 'عطور شرقية', key: 'oriental-perfumes' },
      { en: "Children's Perfumes", ar: 'عطور الأطفال', key: 'kids-perfumes' },
      { en: 'Gift Sets', ar: 'مجموعة هدايا', key: 'gift-sets' },
      { en: 'Luxury Perfumes', ar: 'عطور فاخرة', key: 'luxury-perfumes' },
      { en: 'Hair Mist', ar: 'معطر الشعر', key: 'hair-mist' },
    ],
  },
  {
    id: 'makeup',
    slug: 'beauty',
    title: { en: 'Makeup', ar: 'المكياج' },
    subs: [
      { en: 'Lipstick', ar: 'أحمر شفاه', key: 'lipstick' },
      { en: 'Eye Makeup', ar: 'مكياج العيون', key: 'eye-makeup' },
      { en: 'Face Makeup', ar: 'مكياج الوجه', key: 'face-makeup' },
      { en: 'Nail Care', ar: 'تجميل الأظافر', key: 'nail-care' },
      { en: 'Eyelashes', ar: 'الرموش', key: 'eyelashes' },
      { en: 'Contact Lenses', ar: 'عدسات لاصقة', key: 'Contact Lenses' },
      { en: 'Makeup Tools', ar: 'أدوات المكياج', key: 'makeup-tools' },
      { en: 'Earrings', ar: 'أقراط', key: 'earrings' },
      { en: 'Beauty Accessories', ar: 'اكسسوارات التجميل', key: 'beauty-accessories' },
    ],
  },
  {
    id: 'baby-diapers',
    slug: 'baby',
    title: { en: 'Baby & Diapers', ar: 'العناية بالأطفال والحفاضات' },
    subs: [
      { en: 'Regular Diapers', ar: 'الحفاضات العادية', key: 'Diapers & Wipes' },
      { en: 'Pull-up Diapers', ar: 'حفاضات كلوت', key: 'Diapers & Wipes' },
      { en: 'Premium Diapers', ar: 'حفاضات العناية الفائقة', key: 'Diapers & Wipes' },
      { en: 'Diaper Changing', ar: 'تغيير الحفاض', key: 'Diapers & Wipes' },
      { en: 'Baby Shampoo', ar: 'شامبو أطفال', key: 'Baby Skincare' },
      { en: 'Baby Skincare', ar: 'العناية ببشرة الأطفال', key: 'Baby Skincare' },
      { en: 'Toddler Care (3+ years)', ar: 'العناية بالأطفال (+3 سنوات)', key: 'toddler-care' },
      { en: 'Baby Wipes', ar: 'مناديل مبللة للأطفال', key: 'Diapers & Wipes' },
      { en: 'Baby Hygiene', ar: 'نظافة الأطفال', key: 'Diapers & Wipes' },
    ],
  },
  {
    id: 'vitamins',
    slug: 'vitamins',
    title: { en: 'Vitamins', ar: 'الفيتامينات' },
    subs: [
      { en: 'Hair Vitamins', ar: 'فيتامينات الشعر', key: 'hair-vitamins' },
      { en: 'Skin Radiance', ar: 'إشراقة البشرة', key: 'skin-radiance' },
      { en: 'Multivitamins', ar: 'فيتامينات متعددة', key: 'Multivitamins' },
      { en: 'Weight Management', ar: 'التحكم في الوزن', key: 'weight-management' },
      { en: 'Pregnancy Care', ar: 'رعاية الحمل', key: 'Maternity Care' },
      { en: 'Kids Health', ar: 'صحة الأطفال', key: 'kids-health' },
      { en: 'Sleep Aids', ar: 'مساعدات النوم', key: 'Sleep Aids' },
      { en: 'Heart Health', ar: 'صحة القلب', key: 'Omega-3' },
      { en: 'Diabetes Care', ar: 'رعاية مرضى السكري', key: 'Diabetes Care' },
    ],
  },
  {
    id: 'skincare',
    slug: 'beauty',
    title: { en: 'Skincare', ar: 'العناية بالبشرة' },
    subs: [
      { en: 'Face Moisturizer', ar: 'مرطب البشرة', key: 'Skincare Products' },
      { en: 'Face Cleanser', ar: 'غسول البشرة', key: 'Skincare Products' },
      { en: 'Sunscreen', ar: 'واقي شمس', key: 'Sunscreen' },
      { en: 'Skin Lightening', ar: 'تفتيح البشرة', key: 'Skincare Products' },
      { en: 'Face Serum', ar: 'سيروم البشرة', key: 'Skincare Products' },
      { en: 'K-Beauty', ar: 'الجمال الكوري', key: 'Skincare Products' },
      { en: 'Face Mask', ar: 'ماسك البشرة', key: 'Skincare Products' },
      { en: 'Natural Skincare', ar: 'منتجات العناية الطبيعية', key: 'Skincare Products' },
      { en: 'Skincare Tools', ar: 'ادوات العناية بالبشرة', key: 'Skincare Products' },
    ],
  },
  {
    id: 'baby-essentials',
    slug: 'baby',
    title: { en: 'Baby Essentials', ar: 'مستلزمات الأطفال' },
    subs: [
      { en: 'Strollers', ar: 'عربات الأطفال', key: 'strollers' },
      { en: 'Baby Safety', ar: 'سلامة الطفل', key: 'baby-safety' },
      { en: 'Baby Toys', ar: 'ألعاب الأطفال', key: 'baby-toys' },
      { en: 'Baby Carriers', ar: 'حمالة الأطفال', key: 'baby-carriers' },
      { en: 'Car Seat', ar: 'مقعد سيارة', key: 'car-seat' },
      { en: 'Baby Walkers', ar: 'مشاية الأطفال', key: 'baby-walkers' },
      { en: 'Swings & Bouncers', ar: 'مراجيح وهزازات للأطفال', key: 'swings-bouncers' },
      { en: 'Baby Cribs', ar: 'سرير الأطفال', key: 'baby-cribs' },
    ],
  },
  {
    id: 'personal-care',
    slug: 'beauty',
    title: { en: 'Personal Care', ar: 'العناية الشخصية' },
    subs: [
      { en: 'Deodorants', ar: 'مزيلات العرق', key: 'deodorants' },
      { en: 'Hair Removal', ar: 'إزالة الشعر', key: 'hair-removal' },
      { en: 'Sexual Health', ar: 'الصحة الجنسية', key: 'sexual-health' },
      { en: 'Oral Care', ar: 'العناية بالفم و الأسنان', key: 'Oral Care' },
      { en: 'Feminine Care', ar: 'العناية النسائية', key: 'feminine-care' },
      { en: 'Body & Bath', ar: 'العناية بالجسم و الإستحمام', key: 'Body Care' },
      { en: 'Personal Hygiene', ar: 'النظافة الشخيصة', key: 'personal-hygiene' },
      { en: 'Razor Blades', ar: 'شفرات الحلاقة', key: 'razor-blades' },
    ],
  },
  {
    id: 'hair-care',
    slug: 'beauty',
    title: { en: 'Hair Care', ar: 'العناية بالشعر' },
    subs: [
      { en: 'Shampoo', ar: 'الشامبو', key: 'Hair Care' },
      { en: 'Conditioner', ar: 'البلسم', key: 'Hair Care' },
      { en: 'Hair Treatments', ar: 'معالجات الشعر', key: 'Hair Care' },
      { en: 'Natural Hair Products', ar: 'منتجات الشعر الطبيعة', key: 'Hair Care' },
      { en: 'Hair Dye', ar: 'صبغة الشعر', key: 'Hair Care' },
      { en: 'Scalp Treatment', ar: 'علاج الشعر وفروة الرأس', key: 'Hair Care' },
      { en: 'Hair Styling', ar: 'تصفيف الشعر', key: 'Hair Care' },
      { en: 'Hair Oil & Serum', ar: 'زيت و سيروم الشعر', key: 'Hair Care' },
      { en: 'Hair Styling Tools', ar: 'أجهزة تصفيف الشعر', key: 'Hair Care' },
    ],
  },
  {
    id: 'baby-milk-food',
    slug: 'baby',
    title: { en: 'Baby Milk & Food', ar: 'حليب وطعام الأطفال' },
    subs: [
      { en: 'Baby Formula', ar: 'حليب الأطفال', key: 'Baby Formula' },
      { en: 'Baby Food', ar: 'طعام الأطفال', key: 'Baby Formula' },
      { en: 'Baby Bottles', ar: 'رضاعات', key: 'baby-bottles' },
      { en: 'Formula Preparation', ar: 'تحضير الحليب', key: 'formula-preparation' },
      { en: 'Pacifiers', ar: 'اللهايات', key: 'pacifiers' },
      { en: 'Feeding Accessories', ar: 'مستلزمات طعام الأطفال', key: 'feeding-accessories' },
      { en: 'Baby Bibs', ar: 'مريلة للأطفال', key: 'baby-bibs' },
      { en: 'High Chairs', ar: 'كراسي طعام الاطفال', key: 'high-chairs' },
    ],
  },
  {
    id: 'sports-nutrition',
    slug: 'vitamins',
    title: { en: 'Sports Nutrition', ar: 'التغذية الرياضية' },
    subs: [
      { en: 'Whey Protein', ar: 'واي بروتين', key: 'Protein Supplements' },
      { en: 'Weight Gainer', ar: 'مكمل زيادة الوزن', key: 'Protein Supplements' },
      { en: 'Creatine', ar: 'كرياتين', key: 'Supplements' },
      { en: 'L-Arginine', ar: 'إل-أرجينين', key: 'Supplements' },
      { en: 'BCAA', ar: 'BCAA', key: 'Supplements' },
      { en: 'Glutamine', ar: 'الجلوتامين', key: 'Supplements' },
      { en: 'Protein Bar', ar: 'بروتين بار', key: 'Protein Supplements' },
      { en: 'Fat Burner', ar: 'حرق الدهون', key: 'Supplements' },
      { en: 'Shaker Bottle', ar: 'زجاجة شيكر', key: 'Supplements' },
    ],
  },
  {
    id: 'medical-devices',
    slug: 'medical',
    title: { en: 'Medical Devices', ar: 'الأجهزة الطبية' },
    subs: [
      { en: 'Diabetes Care', ar: 'رعاية السكري', key: 'Diabetes Care' },
      { en: 'Heart Monitors', ar: 'أجهزة مراقبة القلب', key: 'Blood Pressure Monitors' },
      { en: 'Thermometer', ar: 'مقياس الحرارة', key: 'Thermometers' },
      { en: 'Massage Devices', ar: 'أجهزة التدليك', key: 'massage-devices' },
      { en: 'Weight Scales', ar: 'قياس الوزن', key: 'weight-scales' },
      { en: 'Health Trackers', ar: 'أجهزة تتبع الصحة', key: 'Blood Pressure Monitors' },
      { en: 'Home Health Tests', ar: 'اختبار الصحة المنزلي', key: 'home-health-tests' },
      { en: 'Foot Spa', ar: 'سبا القدم', key: 'Body Care' },
    ],
  },
  {
    id: 'home-healthcare',
    slug: 'firstaid',
    title: { en: 'Home Healthcare', ar: 'الرعاية الصحية المنزلية' },
    subs: [
      { en: 'Body Support', ar: 'دعم الجسم', key: 'Bandages & Gauze' },
      { en: 'Pillows & Cushions', ar: 'وسائد ومخدات', key: 'pillows-cushions' },
      { en: 'Face Masks', ar: 'الكمامات و أقنعة الوجه', key: 'Face Masks' },
      { en: 'Cold & Hot Compress', ar: 'كمادات باردة وساخنة', key: 'First Aid Kits' },
      { en: 'Wound Care', ar: 'العناية بالجروح', key: 'Bandages & Gauze' },
      { en: 'Adult Care', ar: 'العناية الصحية للبالغين', key: 'adult-care' },
      { en: 'Wheelchairs & Scooters', ar: 'الكراسي المتحركة والسكوتر', key: 'wheelchairs-scooters' },
      { en: 'Bathroom Safety', ar: 'السلامة في الحمام', key: 'bathroom-safety' },
      { en: 'Medical Beds', ar: 'سرير طبي', key: 'medical-beds' },
    ],
  },
  {
    id: 'healthy-nutrition',
    slug: 'vitamins',
    title: { en: 'Healthy Nutrition', ar: 'التغذية الصحية' },
    subs: [
      { en: 'Honey', ar: 'العسل', key: 'honey' },
      { en: 'Protein Bar', ar: 'بروتين بار', key: 'Protein Supplements' },
      { en: 'Diet Chocolate', ar: 'شوكولاتة دايت', key: 'diet-chocolate' },
      { en: 'Hydration Drinks', ar: 'مشروبات الإرواء', key: 'hydration-drinks' },
      { en: 'Sweeteners', ar: 'المُحليات', key: 'sweeteners' },
      { en: 'Meal Replacement', ar: 'بديل الوجبات', key: 'meal-replacement' },
      { en: 'Natural Water', ar: 'مياه طبيعية', key: 'natural-water' },
      { en: 'Tea & Herbs', ar: 'الشاي و الأعشاب', key: 'Digestive Health' },
    ],
  },
  {
    id: 'women-care',
    slug: 'beauty',
    title: { en: "Women's Care", ar: 'العناية النسائية' },
    subs: [
      { en: 'Sanitary Pads', ar: 'الفوط الصحية', key: 'sanitary-pads' },
      { en: 'Razors & Blades', ar: 'الامواس وشفرات الحلاقة', key: 'razors-blades' },
      { en: 'Waxing', ar: 'الشمع والحلاوة', key: 'waxing' },
      { en: 'Hair Removal Devices', ar: 'أجهزة أزالة الشعر', key: 'hair-removal-devices' },
      { en: 'Hair Removal', ar: 'إزالة الشعر الزائد', key: 'hair-removal-plus' },
      { en: 'Panty Liners', ar: 'الفوط اليومية', key: 'panty-liners' },
      { en: 'Intimate Care', ar: 'غسول ومناديل حميمة', key: 'intimate-care' },
      { en: 'Tampons', ar: 'سدادات قطنية', key: 'tampons' },
      { en: "Women's Multivitamins", ar: 'فيتامينات متعددة للسيدات', key: 'Multivitamins' },
      { en: 'Pregnancy Care', ar: 'العناية بالحمل', key: 'Maternity Care' },
      { en: 'Period Comfort', ar: 'الراحة أثناء الدورة الشهرية', key: 'period-comfort' },
    ],
  },
  {
    id: 'body-bath',
    slug: 'beauty',
    title: { en: 'Body & Bath Care', ar: 'العناية بالجسم والاستحمام' },
    subs: [
      { en: 'Bath Salt', ar: 'حمام الملح', key: 'Body Care' },
      { en: 'Body Lotion', ar: 'لوشن الجسم', key: 'Body Care' },
      { en: 'Body Mist', ar: 'عطر الجسم', key: 'Body Care' },
      { en: 'Body Scrub', ar: 'مقشر الجسم', key: 'Body Care' },
      { en: 'Hand Wash', ar: 'غسول اليد', key: 'Body Care' },
      { en: 'Shower Gel', ar: 'جل استحمام', key: 'Body Care' },
      { en: 'Soap', ar: 'صابون', key: 'Body Care' },
    ],
  },
];

export const categoryLink = (lang, slug) => `/products?category=${encodeURIComponent(slug)}`;

export const subcategoryLink = (lang, slug, sub) =>
  `/products?category=${encodeURIComponent(slug)}&subcategory=${encodeURIComponent(sub.key)}&name=${encodeURIComponent(sub[lang])}`;

export const findCategoryBySlug = (slug) => CATEGORY_DIRECTORY.find((c) => c.slug === slug);

export const findSubcategoryByKey = (key) => {
  for (const cat of CATEGORY_DIRECTORY) {
    const sub = cat.subs.find((s) => s.key === key);
    if (sub) return { category: cat, sub };
  }
  return null;
};
